### ISSUE TITLE
Not all types are reflected to changelog

### ISSUE THREAD

**Issue by Hoishin** [azu/conventional-changelog-angular-all#1]
[Angular commit guideline](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type) has `build: ` and `ci: ` but they are ignored in this preset.

**Comment by azu** [comment]
Probably, we need to add `build` and `ci` to following:
https://github.com/azu/conventional-changelog-angular-all/blob/c8674e77b23edd9b820febe8d7b869a06a68db3c/writer-opts.js#L34-L54

**Comment by azu** [comment]
closed by #2
